[package]
name = "policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
toml = "0.8"

[dev-dependencies]
serde_json.workspace = true
